# ~/.config/starship.toml

add_newline = false
format = """
$directory$git_branch$git_status$nodejs$python$cmd_duration
$character
"""

[directory]
style = "bold blue"

[git_status]
disabled = false

[git_branch]
symbol = "🌱 "

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
 
